Repository kharms-dev/discord-power-bot, pull requests merged in 2022-11, with the labels that each got.

#15 Feature/cooldowns
  .env.example
  app/bot.py
Labels: enhancement

#21 Fixed indentation error on cache workflow
  .github/workflows/lint-and-test.yaml
Labels: bug

#22 [Fix] Load pytest as a module, as not in GH Actions builder path
  Pipfile
Labels: bug

#25 Added sudo command to force a power function to be run, regardless of…
  app/bot.py
Labels: enhancement

#28 GitHub actions fixes
  .github/workflows/codeql.yml
  .github/workflows/lint-and-test.yaml
  .github/workflows/release.yaml
  Pipfile
  Pipfile.lock
  tests/test_servers.py
Labels: bug, enhancement
